#
# @OSF_FREE_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1992, 1991, 1990  
# Open Software Foundation, Inc. 
#  
# Permission is hereby granted to use, copy, modify and freely distribute 
# the software in this file and its documentation for any purpose without 
# fee, provided that the above copyright notice appears in all copies and 
# that both the copyright notice and this permission notice appear in 
# supporting documentation.  Further, provided that the name of Open 
# Software Foundation, Inc. ("OSF") not be used in advertising or 
# publicity pertaining to distribution of the software without prior 
# written permission from OSF.  OSF makes no representations about the 
# suitability of this software for any purpose.  It is provided "as is" 
# without express or implied warranty. 
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.2.3  1992/12/03  19:08:43  damon
# 	ODE 2.2 CR 346. Expanded copyright
# 	[1992/12/03  18:37:53  damon]
#
# Revision 1.1.2.2  1992/04/13  15:45:53  damon
# 	Initial Version
# 	[1992/04/13  15:45:23  damon]
# 
# $EndLog$

PROGRAMS		= copyscan

ILIST			= copyscan
IDIR			= /bin/

LIBS			= -lode

.include <${RULES_MK}>
