#
# @OSF_FREE_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1992, 1991, 1990  
# Open Software Foundation, Inc. 
#  
# Permission is hereby granted to use, copy, modify and freely distribute 
# the software in this file and its documentation for any purpose without 
# fee, provided that the above copyright notice appears in all copies and 
# that both the copyright notice and this permission notice appear in 
# supporting documentation.  Further, provided that the name of Open 
# Software Foundation, Inc. ("OSF") not be used in advertising or 
# publicity pertaining to distribution of the software without prior 
# written permission from OSF.  OSF makes no representations about the 
# suitability of this software for any purpose.  It is provided "as is" 
# without express or implied warranty. 
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.2.2  1993/03/17  16:00:12  damon
# 	CR 436. Initial Version
# 	[1993/03/17  15:49:38  damon]
#
# Revision 1.1.2.1  1993/03/17  16:00:11  damon
# *** Initial Branch Revision ***
#
# $EndLog$

PROGRAMS		= bsubmit_s

ILIST			= bsubmit_s
IDIR			= /server/

LIBS			= -lode

HFILES			= bsubmit.h

.include <${RULES_MK}>
