#
# @OSF_FREE_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1992, 1991, 1990  
# Open Software Foundation, Inc. 
#  
# Permission is hereby granted to use, copy, modify and freely distribute 
# the software in this file and its documentation for any purpose without 
# fee, provided that the above copyright notice appears in all copies and 
# that both the copyright notice and this permission notice appear in 
# supporting documentation.  Further, provided that the name of Open 
# Software Foundation, Inc. ("OSF") not be used in advertising or 
# publicity pertaining to distribution of the software without prior 
# written permission from OSF.  OSF makes no representations about the 
# suitability of this software for any purpose.  It is provided "as is" 
# without express or implied warranty. 
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.8.5.1  1994/02/08  15:27:57  damon
# 	CR 1029. Install release notes into doc area
# 	[1994/02/08  15:27:47  damon]
#
# Revision 1.8.2.3  1992/12/03  19:09:02  damon
# 	ODE 2.2 CR 346. Expanded copyright
# 	[1992/12/03  18:40:37  damon]
# 
# Revision 1.8.2.2  1992/11/18  15:32:40  damon
# 	CR 12. Changed dug to users.gd
# 	[1992/11/18  15:32:28  damon]
# 
# Revision 1.8  1991/12/05  20:55:17  devrcs
# 	Added _FREE_ to copyright marker
# 	[91/08/01  08:09:13  mckeen]
# 
# 	Modified to build in ODE 2.1
# 	[91/07/17  10:00:11  mckeen]
# 
# 	Changes for Reno make
# 	[91/03/22  16:17:50  mckeen]
# 
# 	Added "sag" subdirectory
# 	[91/02/13  17:30:51  marty]
# 
# 	Cleaned up for project ode
# 	[91/01/09  13:03:37  mckeen]
# 
# Revision 1.7  90/10/07  21:53:24  devrcs
# 	Added EndLog Marker.
# 	[90/09/29  14:07:58  gm]
# 
# Revision 1.6  90/08/09  14:42:16  devrcs
# 	Cleanup for export, install and post-freeze.
# 	[90/08/05  13:40:49  gm]
# 
# $EndLog$

SUBDIRS			= tools users.gd sag release_notes

.include <${RULES_MK}>
