#
# @OSF_FREE_COPYRIGHT@
# 
# Copyright Hewlett-Packard Company 1993 
#
# To anyone who acknowledges that this software is provided "as is"
# without any express or implied warranty, permission to use, copy,
# modify, and distribute this software for any purpose is hereby
# granted without fee, provided that the above copyright notice and
# this notice appears in all copies, and that the name of
# Hewlett-Packard Company not be used in advertising or publicity
# pertaining to distribution of the software without specific,
# written prior permission.  Hewlett-Packard Company makes no
# representations about the suitability of this software for any
# purpose.
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.2.2  1993/01/20  19:57:44  ezf
# 	ODE version of makefile
# 	[1993/01/20  19:56:56  ezf]
#
# $EndLog$

PROGRAMS= rcstramp
ILIST=    ${PROGRAMS}
IDIR=     /bin/
OFILES=   rcstramp.o env.o

.include <${RULES_MK}>
