#
# @OSF_FREE_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1992, 1991, 1990  
# Open Software Foundation, Inc. 
#  
# Permission is hereby granted to use, copy, modify and freely distribute 
# the software in this file and its documentation for any purpose without 
# fee, provided that the above copyright notice appears in all copies and 
# that both the copyright notice and this permission notice appear in 
# supporting documentation.  Further, provided that the name of Open 
# Software Foundation, Inc. ("OSF") not be used in advertising or 
# publicity pertaining to distribution of the software without prior 
# written permission from OSF.  OSF makes no representations about the 
# suitability of this software for any purpose.  It is provided "as is" 
# without express or implied warranty. 
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.10.4.2  1993/03/17  21:59:18  damon
# 	CR 447. Changed etc to server
# 	[1993/03/17  21:58:15  damon]
#
# Revision 1.10.4.1  1993/03/17  21:59:17  damon
# *** Initial Branch Revision ***
#
# Revision 1.10.2.2  1992/12/03  19:03:26  damon
# 	ODE 2.2 CR 346. Expanded copyright
# 	[1992/12/03  18:33:26  damon]
# 
# Revision 1.10  1991/12/17  20:57:30  devrcs
# 	Changed order of doc and man so that man pages get built first
# 	so that they can be included in the common dug
# 	[1991/12/09  19:31:37  mckeen]
# 
# Revision 1.9  1991/12/05  20:38:56  devrcs
# 	Changes for Reno make
# 	[91/03/22  15:29:49  mckeen]
# 
# 	Creations/Fixes for project ode lbe
# 	[91/01/17  16:44:09  mckeen]
# 
# 	Cleaned up for project ode
# 	[91/01/09  13:01:37  mckeen]
# 
# 	Initial project ODE revision
# 	[91/01/08  17:18:51  mckeen]
# 
# Revision 1.8  90/10/07  21:48:40  devrcs
# 	Added EndLog Marker.
# 	[90/09/29  14:01:02  gm]
# 
# Revision 1.7  90/08/09  14:40:45  devrcs
# 	Cleanup for export, install and post-freeze.
# 	[90/08/05  13:40:26  gm]
# 
# $EndLog$

SUBDIRS			= lib include bin server man doc

EXPLIB_SUBDIRS		= lib
EXPINC_SUBDIRS		= include

.include <${RULES_MK}>
