#
# @OSF_FREE_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1992, 1991, 1990  
# Open Software Foundation, Inc. 
#  
# Permission is hereby granted to use, copy, modify and freely distribute 
# the software in this file and its documentation for any purpose without 
# fee, provided that the above copyright notice appears in all copies and 
# that both the copyright notice and this permission notice appear in 
# supporting documentation.  Further, provided that the name of Open 
# Software Foundation, Inc. ("OSF") not be used in advertising or 
# publicity pertaining to distribution of the software without prior 
# written permission from OSF.  OSF makes no representations about the 
# suitability of this software for any purpose.  It is provided "as is" 
# without express or implied warranty. 
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1994/02/24  21:53:23  marty
# 	CR # 1064 - add an entry for supfilesrv
# 	[1994/02/24  21:53:10  marty]
#
# Revision 1.1.4.1  1994/02/17  16:31:00  damon
# 	CR 1056. Added supscan
# 	[1994/02/17  16:30:29  damon]
# 
# Revision 1.1.2.7  1993/05/13  15:50:22  damon
# 	CR. Added logsubmit,rcsacl,srcacl to server dir
# 	[1993/05/13  15:50:05  damon]
# 
# Revision 1.1.2.6  1993/05/03  20:15:25  damon
# 	CR 436. Added bco_s
# 	[1993/05/03  20:15:13  damon]
# 
# Revision 1.1.2.5  1993/04/08  23:23:50  damon
# 	CR 436. Added bmerge_s
# 	[1993/04/08  23:23:44  damon]
# 
# Revision 1.1.2.4  1993/04/08  23:07:52  damon
# 	CR 436. Added bmerge_s
# 	[1993/04/08  23:07:45  damon]
# 
# Revision 1.1.2.3  1993/03/19  17:15:36  marty
# 	Add bstat_s and bcs_s to SUBDIRS.
# 	[1993/03/19  17:13:35  marty]
# 
# Revision 1.1.2.2  1993/03/17  22:00:09  damon
# 	CR 436. New Makefile
# 	[1993/03/17  21:58:33  damon]
# 
# $EndLog$

SUBDIRS			= bco_s bcs_s blog_s bmerge_s branch_ci bstat_s \
		          bsubmit_s logsubmit odexm rcsacl srcacl supscan \
			  supfilesrv
                          

.include <${RULES_MK}>
