#
# @OSF_FREE_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1992, 1991, 1990  
# Open Software Foundation, Inc. 
#  
# Permission is hereby granted to use, copy, modify and freely distribute 
# the software in this file and its documentation for any purpose without 
# fee, provided that the above copyright notice appears in all copies and 
# that both the copyright notice and this permission notice appear in 
# supporting documentation.  Further, provided that the name of Open 
# Software Foundation, Inc. ("OSF") not be used in advertising or 
# publicity pertaining to distribution of the software without prior 
# written permission from OSF.  OSF makes no representations about the 
# suitability of this software for any purpose.  It is provided "as is" 
# without express or implied warranty. 
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.6.5.1  1993/12/16  00:07:00  marty
# 	CR # 856 - Add odexm man page.
# 	[1993/12/16  00:06:44  marty]
#
# Revision 1.6.2.2  1992/12/03  17:25:27  damon
# 	ODE 2.2 CR 183. Added CMU notice
# 	[1992/12/03  17:10:46  damon]
# 
# Revision 1.6  1991/12/05  21:17:17  devrcs
# 	change sandboxrc to oderc
# 	[1991/11/05  21:44:01  mckeen]
# 
# 	Added _FREE_ to copyright marker
# 	[91/08/01  08:17:47  mckeen]
# 
# 	Added cat directories and set man directories to only build sources
# 	[91/07/30  13:08:05  mckeen]
# 
# 	Install .mm sources instead of cat files
# 	[91/04/19  11:01:41  mckeen]
# 
# 	Changes for Reno make
# 	[91/03/22  16:35:33  mckeen]
# 
# 	Cleaned up for project ode
# 	[91/01/09  13:08:10  mckeen]
# 
# Revision 1.5  90/10/07  21:59:16  devrcs
# 	Added EndLog Marker.
# 	[90/09/29  14:17:13  gm]
# 
# Revision 1.4  90/08/09  14:42:53  devrcs
# 	Cleanup for export, install and post-freeze.
# 	[90/08/05  13:41:27  gm]
# 
# $EndLog$

MANSOURCE		= makefiles oderc odexm

ILIST			= ${MANSOURCE:=.5}
IDIR			= /man/man5/
IMODE			= 444

.include <${RULES_MK}>
