#
# @OSF_FREE_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1992, 1991, 1990  
# Open Software Foundation, Inc. 
#  
# Permission is hereby granted to use, copy, modify and freely distribute 
# the software in this file and its documentation for any purpose without 
# fee, provided that the above copyright notice appears in all copies and 
# that both the copyright notice and this permission notice appear in 
# supporting documentation.  Further, provided that the name of Open 
# Software Foundation, Inc. ("OSF") not be used in advertising or 
# publicity pertaining to distribution of the software without prior 
# written permission from OSF.  OSF makes no representations about the 
# suitability of this software for any purpose.  It is provided "as is" 
# without express or implied warranty. 
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.4.6.1  1993/11/16  02:30:50  marty
# 	CR # 812 - Remove sindex from Makefile,.
# 	[1993/11/16  02:30:30  marty]
#
# Revision 1.4.4.1  1993/09/14  13:30:29  marty
# 	CR # 623
# 	[1993/09/14  13:30:16  marty]
# 
# Revision 1.4.2.2  1992/12/03  17:24:56  damon
# 	ODE 2.2 CR 183. Added CMU notice
# 	[1992/12/03  17:10:31  damon]
# 
# Revision 1.4  1991/12/05  21:15:55  devrcs
# 	Added _FREE_ to copyright marker
# 	[91/08/01  08:15:36  mckeen]
# 
# 	Added cat directories and set man directories to only build sources
# 	[91/07/30  13:07:59  mckeen]
# 
# 	Install mm sources instaed of cat files
# 	[91/04/19  11:01:36  mckeen]
# 
# 	Changes for Reno make
# 	[91/03/22  16:35:27  mckeen]
# 
# 	Cleaned up for project ode
# 	[91/01/09  13:08:04  mckeen]
# 
# Revision 1.3  90/10/07  21:57:22  devrcs
# 	Added EndLog Marker.
# 	[90/09/29  14:14:04  gm]
# 
# Revision 1.2  90/08/25  12:22:20  devrcs
# 	Initial Revision
# 	[90/08/17  10:28:10  randyb]
# 
# $EndLog$

MANSOURCE		= abspath concat def_build editor fdate filecopy \
			  fold getbool getstr interface makepath match \
			  nxtarg par_rc_file path prstab quit run \
			  sbdata searchp skipto stablk stlmatch \
			  stubs uquit

ILIST			= ${MANSOURCE:=.3}
IDIR			= /man/man3/
IMODE			= 444

.include <${RULES_MK}>




