#
# @OSF_FREE_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1992, 1991, 1990  
# Open Software Foundation, Inc. 
#  
# Permission is hereby granted to use, copy, modify and freely distribute 
# the software in this file and its documentation for any purpose without 
# fee, provided that the above copyright notice appears in all copies and 
# that both the copyright notice and this permission notice appear in 
# supporting documentation.  Further, provided that the name of Open 
# Software Foundation, Inc. ("OSF") not be used in advertising or 
# publicity pertaining to distribution of the software without prior 
# written permission from OSF.  OSF makes no representations about the 
# suitability of this software for any purpose.  It is provided "as is" 
# without express or implied warranty. 
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.10.2.2  1992/12/03  17:23:23  damon
# 	ODE 2.2 CR 183. Added CMU notice
# 	[1992/12/03  17:09:47  damon]
#
# Revision 1.10  1991/12/05  21:13:52  devrcs
# 	added man8 subdirectory for server manual pages
# 	[91/10/21  13:47:53  ezf]
# 
# 	Added _FREE_ to copyright marker
# 	[91/08/01  08:14:12  mckeen]
# 
# 	Added cat directories
# 	[91/07/30  13:04:14  mckeen]
# 
# 	Changes for Reno make
# 	[91/03/22  16:19:17  mckeen]
# 
# 	Cleaned up for project ode
# 	[91/01/09  13:07:46  mckeen]
# 
# Revision 1.9  90/10/07  21:55:39  devrcs
# 	Added EndLog Marker.
# 	[90/09/29  14:11:19  gm]
# 
# Revision 1.8  90/08/09  14:42:35  devrcs
# 	Cleanup for export, install and post-freeze.
# 	[90/08/05  13:41:16  gm]
# 
# $EndLog$

SUBDIRS			= man1 man3 man5 man8 cat1 cat3 cat5 cat8

.include <${RULES_MK}>
