#
# @OSF_FREE_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1992, 1991, 1990  
# Open Software Foundation, Inc. 
#  
# Permission is hereby granted to use, copy, modify and freely distribute 
# the software in this file and its documentation for any purpose without 
# fee, provided that the above copyright notice appears in all copies and 
# that both the copyright notice and this permission notice appear in 
# supporting documentation.  Further, provided that the name of Open 
# Software Foundation, Inc. ("OSF") not be used in advertising or 
# publicity pertaining to distribution of the software without prior 
# written permission from OSF.  OSF makes no representations about the 
# suitability of this software for any purpose.  It is provided "as is" 
# without express or implied warranty. 
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.9.2.2  1992/12/03  19:10:08  damon
# 	ODE 2.2 CR 346. Expanded copyright
# 	[1992/12/03  18:41:16  damon]
#
# Revision 1.9  1991/12/05  20:55:40  devrcs
# 	Added _FREE_ to copyright marker
# 	[91/08/01  08:09:18  mckeen]
# 
# 	Changes for Reno make
# 	[91/03/22  19:15:35  mckeen]
# 
# $EndLog$

SUBDIRS			= common dce osc

.include <${RULES_MK}>
