#
# @OSF_FREE_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1992, 1991, 1990  
# Open Software Foundation, Inc. 
#  
# Permission is hereby granted to use, copy, modify and freely distribute 
# the software in this file and its documentation for any purpose without 
# fee, provided that the above copyright notice appears in all copies and 
# that both the copyright notice and this permission notice appear in 
# supporting documentation.  Further, provided that the name of Open 
# Software Foundation, Inc. ("OSF") not be used in advertising or 
# publicity pertaining to distribution of the software without prior 
# written permission from OSF.  OSF makes no representations about the 
# suitability of this software for any purpose.  It is provided "as is" 
# without express or implied warranty. 
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.2.2.2  1992/12/03  17:23:40  damon
# 	ODE 2.2 CR 183. Added CMU notice
# 	[1992/12/03  17:09:54  damon]
#
# Revision 1.2  1991/12/05  21:14:04  devrcs
# 	created Makefile for formatted server man pages
# 	[91/10/22  12:41:19  ezf]
# 
# $EndLog$

VPATH			= ../man8

MANPAGES		= supfilesrv
MANSECTION		= 8

ILIST			= ${MANPAGES:=.0}
IDIR			= /man/cat8/
IMODE			= 444

.include <${RULES_MK}>
