#
# @OSF_FREE_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1992, 1991, 1990  
# Open Software Foundation, Inc. 
#  
# Permission is hereby granted to use, copy, modify and freely distribute 
# the software in this file and its documentation for any purpose without 
# fee, provided that the above copyright notice appears in all copies and 
# that both the copyright notice and this permission notice appear in 
# supporting documentation.  Further, provided that the name of Open 
# Software Foundation, Inc. ("OSF") not be used in advertising or 
# publicity pertaining to distribution of the software without prior 
# written permission from OSF.  OSF makes no representations about the 
# suitability of this software for any purpose.  It is provided "as is" 
# without express or implied warranty. 
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.2.5.1  1994/02/11  17:35:51  root
# 	CR # 1049 - Build warnings and error on ALPHA
# 	[1994/02/11  17:35:28  root]
#
# Revision 1.2.2.2  1992/12/03  19:09:43  damon
# 	ODE 2.2 CR 346. Expanded copyright
# 	[1992/12/03  18:41:07  damon]
# 
# Revision 1.2  1991/12/05  21:03:20  devrcs
# 	Modified to build in ODE 2.1
# 	[91/07/17  10:00:25  mckeen]
# 
# $EndLog$

PROGRAMS	= mmindex

#mmindex_CCTYPE	= host

.include <${RULES_MK}>

