#
# @OSF_FREE_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1992, 1991, 1990  
# Open Software Foundation, Inc. 
#  
# Permission is hereby granted to use, copy, modify and freely distribute 
# the software in this file and its documentation for any purpose without 
# fee, provided that the above copyright notice appears in all copies and 
# that both the copyright notice and this permission notice appear in 
# supporting documentation.  Further, provided that the name of Open 
# Software Foundation, Inc. ("OSF") not be used in advertising or 
# publicity pertaining to distribution of the software without prior 
# written permission from OSF.  OSF makes no representations about the 
# suitability of this software for any purpose.  It is provided "as is" 
# without express or implied warranty. 
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.2.2.2  1992/12/03  17:23:36  damon
# 	ODE 2.2 CR 183. Added CMU notice
# 	[1992/12/03  17:09:52  damon]
#
# Revision 1.2  1991/12/05  21:14:01  devrcs
# 	change sandboxrc to oderc
# 	[1991/11/05  21:54:05  mckeen]
# 
# 	created cat directories to build formated manpages in
# 	[91/07/30  13:04:28  mckeen]
# 
# $EndLog$

VPATH			= ../man5

MANPAGES		= makefiles oderc
MANSECTION		= 5

ILIST			= ${MANPAGES:=.0}
IDIR			= /man/cat5/
IMODE			= 444

.include <${RULES_MK}>
