# COPYRIGHT NOTICE
# Copyright (c) 1994-1990 Open Software Foundation, Inc.
# 
# Permission is hereby granted to use, copy, modify and freely distribute
# the software in this file and its documentation for any purpose without
# fee, provided that the above copyright notice appears in all copies and
# that both the copyright notice and this permission notice appear in
# supporting documentation.  Further, provided that the name of Open
# Software Foundation, Inc. ("OSF") not be used in advertising or
# publicity pertaining to distribution of the software without prior
# written permission from OSF.  OSF makes no representations about the
# suitability of this software for any purpose.  It is provided "as is"
# without express or implied warranty.
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.9.1  1994/02/08  17:21:02  damon
# 	Added CPY NOTICE
# 	[1994/02/08  17:20:53  damon]
#
# Revision 1.1.4.7  1993/05/06  18:43:01  marty
# 	test
# 	[1993/05/06  18:42:47  marty]
# 
# 	merge up
# 	[1993/05/05  20:44:40  marty]
# 
# Revision 1.1.4.5  1993/04/15  20:18:46  marty
# 	testig
# 	[1993/04/15  20:18:36  marty]
# 
# Revision 1.1.4.4  1993/02/23  18:30:12  marty
# 	Done testing.
# 	[1993/02/23  18:29:27  marty]
# 
# Revision 1.1.4.3  1993/02/23  18:27:27  marty
# 	 testing bmerge
# 	[1993/02/23  18:27:11  marty]
# 
# Revision 1.1.4.2  1993/01/14  18:49:06  damon
# 	Got nuked again! Replacing again
# 	[1993/01/14  18:48:47  damon]
# 
# Revision 1.1.2.2  1992/05/08  13:50:09  damon
# 	This file somehow got nuked. Replacing it.
# 	[1992/05/08  13:49:48  damon]
# 
# $EndLog$

SUBDIRS			= ode
EXPINC_SUBDIRS		= ode
EXPLIB_SUBDIRS		= ode

.include <${RULES_MK}>


